### ISSUE TITLE
running Dockerfile import error for snowboy.so

### ISSUE THREAD

**Issue by DocksDocks** [seasalt-ai/snowboy#22]
Hello I was just using your Dockerfile to able to make my 'hotword.pmdl' and went through some problems

First problem was that in the last version released for scipy in python2 depends on numpy and mkv to be built

I simply resolved this by adding pip install for numpy and mkv
```
    . venv/snowboy/bin/activate && \
    cd examples/Python && \
    pip install numpy && \
    pip install mkv && \
    pip install -r requirements.txt
```

But then i built my docker image with  
```
sudo docker build -t snowboy-pmdl .
```
And ran it
```
sudo docker run -it -v $(pwd)/model:/snowboy-master/examples/Python/model snowboy-pmdl
```
I got this import error for snowboy.so
```
Traceback (most recent call last):
  File "generate_pmdl.py", line 7, in <module>
    from pmdl.snowboy_pmdl import SnowboyPersonalEnroll, SnowboyTemplateCut
  File "/snowboy-master/examples/Python/pmdl/snowboy_pmdl.py", line 10, in <module>
    from snowboy import *
  File "/snowboy-master/examples/Python/pmdl/lib/ubuntu64/pmdl/snowboy.py", line 28, in <module>
    _snowboy = swig_import_helper()
  File "/snowboy-master/examples/Python/pmdl/lib/ubuntu64/pmdl/snowboy.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboy', fp, pathname, description)
ImportError: /snowboy-master/examples/Python/pmdl/lib/ubuntu64/pmdl/_snowboy.so: cannot open shared object file: No such file or directory
```

I actually didnt get how to solve this problem, if anyone could help me I would be very grateful

**Comment by AlaaAhmed1993** [comment]
u
